### ISSUE TITLE
Release v0.1.0 with TS data structure

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSFrames.jl#108]
Before renaming `TS` to `TimeFrame` and the package to TimeFrames.jl (issue #66) we should do a release with existing name and data structure to enable existing users to migrate to the new name.

**Comment by chiraganand** [comment]
PR #111 is merged.

**Comment by chiraganand** [comment]
> Registration PR: [JuliaRegistries/General#71350](https://github.com/JuliaRegistries/General/pull/71350)

This will need to be closed and a new PR should be created with the registry.

**Comment by codetalker7** [comment]
PR with new package name created: https://github.com/JuliaRegistries/General/pull/72041

**Comment by chiraganand** [comment]
Registration is complete. I can install the package now using `Pkg.add("TSFrames")`.
