### ISSUE TITLE
TSFrames not working in Julia 1.6

### ISSUE THREAD

**Issue by enweg** [xKDR/TSFrames.jl#162]
I am trying to use TSFrames in a package I am currently developing and noticed that my tests fail in Julia 1.6. It seems like this is due to the following line.:

https://github.com/xKDR/TSFrames.jl/blob/305267dd2bd1ddcc94253e97efe01621e6d0cac5/src/subset.jl#L142

As much as I can see and find online (see [this](https://discourse.julialang.org/t/broadcasting-of-logical-operators-in-v1-6-vs-v1-7/75772) discussion), broadcasting of `&&` is not supported in Julia 1.6. Is there a nice way to fix this, or should TSFrames restate its compatibility to 1.7 and beyond? It currently seems to state 1.6: 

https://github.com/xKDR/TSFrames.jl/blob/305267dd2bd1ddcc94253e97efe01621e6d0cac5/Project.toml#L24

**Comment by chiraganand** [comment]
I think for now we will just keep the compatibility to Julia v1.7. I don't have the time right now to look into this. Will do as soon as I can.
