### ISSUE TITLE
Implement doing regressions using `rollapply()`

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSFrames.jl#49]
It is not possible to currently run multiple regressions using `rollapply()` because RollingFunctions.jl does not support rolling over tables.

Example code:
```julia
function regress(data)
        ll = lm(@formula(inrchf ~ usdchf + eurchf + gbpchf + jpychf), data)
        co = coef(ll)[coefnames(ll) .== "usdchf"]
        sd = Statistics.std(residuals(ll))
        return Dict("coeff" => co, "sd" => sd)
      end

rollapply(regress, returns, 200) // doesn't work
```

**Comment by codetalker7** [comment]
@chiraganand in the above example, could you provide the full code, mainly what the `returns` variable is?

**Comment by chiraganand** [comment]
`returns` is a `TSFrame` with the following columns: `inrchf`, `usdchf`, `eurchf`, `gbpchf`, and `jpychf`. The regression formula in the `regress()` function uses the names of these columns to run identify the response and predictor variables. The issue with RollingFunctions.jl is that it only works on a vector, hence, loses the column name information which is needed for running `lm()`.

**Comment by chiraganand** [comment]
The method signature is: `rollapply(fun::Function, tsf::TSFrame, window::Int)`.

**Comment by codetalker7** [comment]
Hi @chiraganand. I'm still a bit confused regarding this issue and the things we discussed last time.

So for the signature `rollapply(fun::Function, tsf::TSFrame, window::Int)`, we aren't specifying what columns to operate on; so by default the assumption is to operate on all columns. So I'm assuming `fun` is a function which operates on a `DataFrame` (certainly `regress` is a function operating on `DataFrame`s)?

So for this kind of problem, how about something like this: 
```julia
# fun must be a function operating on a DataFrame
function rollapply(fun::Function, ts::TSFrame, windowsize::Int)
    res = [fun(ts.coredata[index - windowsize + 1:index, Not(:Index)]) for index in windowsize:TSFrames.nrow(ts)]
    idx = TSFrames.index(ts)[windowsize:end]
    res_df = DataFrame([idx, res], ["Index", "rolling_$(fun)"])
    return TSFrame(res_df)
end
```

**Comment by chiraganand** [comment]
> Hi @chiraganand. I'm still a bit confused regarding this issue and the things we discussed last time.
> 
> So for the signature `rollapply(fun::Function, tsf::TSFrame, window::Int)`, we aren't specifying what columns to operate on; so by default the assumption is to operate on all columns.

`rollapply()` doesn't decide which columns to operate on but the user function `fun` decides that.

> So I'm assuming `fun` is a function which operates on a `DataFrame` (certainly `regress` is a function operating on `DataFrame`s)?

The internal implementation of `rollapply()` applies `fun` on the `coredata` DataFrame excluding the `:Index` column but for the end-user `fun` operates on the `TSFrame` object.

> So for this kind of problem, how about something like this:
> 
> ```julia
> # fun must be a function operating on a DataFrame
> function rollapply(fun::Function, ts::TSFrame, windowsize::Int)
>     res = [fun(ts.coredata[index - windowsize + 1:index, Not(:Index)]) for index in windowsize:TSFrames.nrow(ts)]
>     idx = TSFrames.index(ts)[windowsize:end]
>     res_df = DataFrame([idx, res], ["Index", "rolling_$(fun)"])
>     return TSFrame(res_df)
> end
> ```

The calculation of index will need to change, see:
```julia
julia> rollapply(median, TSFrame(1:10), 2)
ERROR: MethodError: no method matching length(::DataFrame)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at ~/apps/julia-1.7.2/share/julia/base/abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/apps/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/adjtrans.jl:171
  length(::Union{Tables.AbstractColumns, Tables.AbstractRow}) at ~/.julia/packages/Tables/T7rHm/src/Tables.jl:180
  ...
Stacktrace:
 [1] _similar_shape(itr::DataFrame, #unused#::Base.HasLength)
   @ Base ./array.jl:600
 [2] _collect(cont::UnitRange{Int64}, itr::DataFrame, #unused#::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:655
 [3] collect(itr::DataFrame)
   @ Base ./array.jl:649
 [4] median(itr::DataFrame)
   @ Statistics ~/apps/julia-1.7.2/share/julia/stdlib/v1.7/Statistics/src/Statistics.jl:855
 [5] (::var"#3#4"{typeof(median), TSFrame, Int64})(index::Int64)
   @ Main ./none:0
 [6] iterate
   @ ./generator.jl:47 [inlined]
 [7] collect
   @ ./array.jl:724 [inlined]
 [8] rollapply(fun::typeof(median), ts::TSFrame, windowsize::Int64)
   @ Main ./REPL[3]:2
 [9] top-level scope
   @ REPL[15]:1
```
